jobs:

- job: Windows
  pool:
    vmImage: vs2017-win2016

  variables:
    os_name: Windows

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
        # run_browser_tests: true
        # browser_name: Edge
        run_coveralls: true

  steps:
  - template: .azure-pipelines-steps.yml

- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'

  variables:
    os_name: Linux

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
        DISPLAY: :99.0
        run_browser_tests: true
        browser_name: Firefox
        run_coveralls: true

  steps:
  - script: |
      /usr/bin/Xvfb $(DISPLAY) -ac >> /tmp/xvfb.out 2>&1 &
      disown -ar
    displayName: 'Start xvfb'
    condition: variables.run_browser_tests

  - template: .azure-pipelines-steps.yml

- job: OSX
  pool:
    vmImage: 'macOS 10.13'

  variables:
    os_name: OSX

  strategy:
    matrix:
      node_6_x:
        node_version: 6.x
      node_8_x:
        node_version: 8.x
      node_10_x:
        node_version: 10.x
        run_browser_tests: true
        browser_name: Safari

  steps:
  - template: .azure-pipelines-steps.yml
